image: tmaier/docker-compose:17.09
services:
  - docker:17.09-dind
variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

before_script:
  #- docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.acolono.net:444
build:
  stage: build
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
