# Docker and Docker Compose based environment for Drupal.
# See https://github.com/docksal/docksal for more information and documentation.

# This is a shared configuration file that is intended to be stored in the project repo.
# For local overrides:
# - create .docksal/docksal-local.yml file and put local docker-compose configuration overrides there
# - add .docksal/docksal-local.yml to .gitignore

# Docksal stiches several docker-compose configuration files together.
# Run "fin config" to see which files are involved and the resulting configration.

version: "2.1"

services:

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: docker.elastic.co/kibana/kibana:5.2.2
    ports:
    - "5601:5601"
    links:
    - elastic
    environment:
    - ELASTICSEARCH_URL=http://elastic:9200
    labels:
    - io.docksal.virtual-host=${VIRTUAL_HOST}
  scrapyd:
      image: vimagick/scrapyd
      ports:
        - "6800:6800"
      links:
          - elastic
      volumes:
            # Project root volume
            - project_root:/hoaxly
