# Docker and Docker Compose based environment for Drupal.
# See https://github.com/docksal/docksal for more information and documentation.

# This is a shared configuration file that is intended to be stored in the project repo.
# For local overrides:
# - create .docksal/docksal-local.yml file and put local docker-compose configuration overrides there
# - add .docksal/docksal-local.yml to .gitignore

# Docksal stiches several docker-compose configuration files together.
# Run "fin config" to see which files are involved and the resulting configration.

version: "2.1"

services:
  elastic:
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elastic
    environment:
      - ELASTICSEARCH_URL=http://elastic:9200

  scrapyd:
    image: vimagick/scrapyd
    ports:
      - "6800:6800"
    depends_on:
      - elastic
    volumes:
      - project_root:/hoaxly

  portia:
    build:
      context: ${PWD}/portia
    image: acolono/portia:bleeding
    ports:
      - "9001:9001"
    volumes:
     # - ./portia/data:/app/slyd/data
      - ${PWD}/portia_projects:/app/data/projects:rw
