#!/usr/bin/env bash




#-------------------------- Execution --------------------------------


if [[ "$PROJECT_ROOT" == "" ]]; then
	echo-red "\$PROJECT_ROOT is not set"
	exit 1
fi

	if [[ -d $PROJECT_ROOT/data ]]; then
		echo-red  "$PROJECT_ROOT/data already exists. aborting"
	fi
mkdir $PROJECT_ROOT/data
git clone git@github.com:scrapinghub/portia.git
cd portia/portiaui
npm install && bower install
cd node_modules/ember-cli && npm install && cd ../../
ember build
cd ..
#-------------------------- End Execution --------------------------------
